### 기본적인 이미지 다루기

In [2]:
### 모듈 로딩
import cv2
import numpy as np

[1] 이미지 데이터 로딩  
    - 컬러 / 회색 이미지 변환 로딩 가능함

In [3]:
file = r'..\data\img\Italian_greyhound\n02091032_55.jpg'

In [4]:
### 컬러 이미지 로딩 [기본값]
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

### 회색 이미지 로딩
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

In [5]:
### 이미지 데이터 정보확인
print(f'[Color IMAGE]')
print(f'SHAPE : {img_rgb.shape}     DIM : {img_rgb.ndim}차원')
print(f'DTYPE : {img_rgb.dtype}     SIZE : {img_rgb.size}바이트\n')

print(f'[Color IMAGE]')
print(f'SHAPE : {img_gray.shape}     DIM : {img_gray.ndim}차원')
print(f'DTYPE : {img_gray.dtype}     SIZE : {img_gray.size}바이트')

[Color IMAGE]
SHAPE : (392, 500, 3)     DIM : 3차원
DTYPE : uint8     SIZE : 588000바이트

[Color IMAGE]
SHAPE : (392, 500)     DIM : 2차원
DTYPE : uint8     SIZE : 196000바이트


In [6]:
### 이미지 창 띄우기
cv2.imshow('[ COLOR ]', img_rgb)

### 이미지 창 제어
# 키보드 입력 대기하는 함수 
# - delay 인자를 주면 지정한 시간 동안 프로그램을 멈추고 대기.
# - 지정한 시간까지 키보드 입력이 없으면 -1 반환
cv2.waitKey()

### 이미지 창 닫기
cv2.destroyAllWindows()

In [7]:
if img_rgb is not None:
    cv2.imshow('IMG', img_rgb)
    while True:
        key = cv2.waitKey()                     # 키 입력 대기
        print(f'key >> {key} - {hex(key)}')     # 입력 키 출력
        
        if key == 27:                   # ESC키일 때 화면 종료
            cv2.destroyAllWindows()
            break
else:
    print('No image file !!!')

key >> 27 - 0x1b


In [8]:
### 회색 이미지 저장
save_filename = '../data/img/greyhound_gray.jpg'
gray_file = cv2.imwrite(save_filename, img_gray)

In [9]:
print(gray_file)    # 저장 성공

True


In [15]:
### 이미지 채널 분리
img_b, img_g, img_r = cv2.split(img_rgb)    # 이미지 채널 분리 B G R

cv2.imshow('[Blue Channel]', img_b)
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[Blue Channel]')

cv2.imshow('[Green Channel]', img_g)
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[Green Channel]')

cv2.imshow('[Red Channel]', img_r)
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[Red Channel]')

In [17]:
### 이미지 채널 분리 (인덱싱 활용)
# ndarray 분리
b, g, r = img_rgb[:, :, 0], img_rgb[:, :, 1], img_rgb[:, :, 2]

cv2.imshow('[IMG-R]', r)
cv2.imshow('[IMG-G]', g)
cv2.imshow('[IMG-B]', b)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
### 이미지 채널 병합
# (b, g, r) 순으로 병합하면 정상적으로 나온다.
img_rgb2 = cv2.merge((r, b, g))     # 채널 순서 변경

cv2.imshow('[RGB IMAGE]', img_rgb2)

cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
### 이미지 색공간 변환
# 이미지 채널 BGR -> HSV
src_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2HSV)

cv2.imshow('[HSV IMG]', src_hsv)

cv2.waitKey()
cv2.destroyAllWindows()

In [27]:
planes = cv2.split(src_hsv)

cv2.imshow('[H Channel]', planes[0])
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[H Channel]')

cv2.imshow('[S Channel]', planes[1])
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[S Channel]')

cv2.imshow('[V Channel]', planes[2])
cv2.waitKey(delay=3000)     # 3초 뒤에 꺼지게 하기
cv2.destroyWindow('[V Channel]')

In [28]:
### 이미지 크기 변경
down_img = cv2.resize(img_rgb, dsize=(30, 30), interpolation=cv2.INTER_AREA)
up_img = cv2.resize(img_rgb, dsize=(0, 0), fx=1.5, fy=1.5, interpolation=cv2.INTER_CUBIC)

cv2.imshow('down_img', down_img)
cv2.imshow('up_img', up_img)
cv2.imshow('ORG', img_rgb)

cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
cv2.imshow('COLOR', img_rgb)

### Windows 속성 중 창이 존재하는지 체크하는 속성 cv2.WMD_PROP_VISIBLE
if cv2.waitKey() or cv2.getWindowProperty('[COLOR]', cv2.WND_PROP_VISIBLE) <1:
    # 이미지 창 닫기
    cv2.destroyAllWindows()

In [55]:
### 도화지 만들기
img_b = np.zeros((500, 500), dtype=np.uint8)
img_b.shape

(500, 500)

In [71]:
### 도화지 만들기
img_w = np.full((500, 500, 3), 255, dtype=np.uint8)     # 크기를 (500, 500)으로 주면 흑백으로만 그려진다.
img_w.shape

(500, 500, 3)

In [72]:
print(img_b)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [52]:
cv2.imshow('BLACK', img_b)
cv2.imshow('WHITE', img_w)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [76]:
### 이미지 데이터에 그림 그리기
### (0, 0)은 왼쪽 위. 
img = img_w
cv2.line(img, (50, 50), (150, 50), (255, 0, 0))
cv2.line(img, (200, 50), (300, 50), (0, 255, 0))
cv2.line(img, (350, 50), (450, 50), (0, 0, 255))

cv2.line(img, (100, 100), (400, 100), (255, 255, 0), 10)
cv2.line(img, (100, 150), (400, 150), (255, 0, 255), 10)
cv2.line(img, (100, 200), (400, 200), (0, 255, 255), 10)
cv2.line(img, (100, 250), (400, 250), (255, 255, 0), 10)
cv2.line(img, (100, 300), (400, 300), (0, 0, 0), 10)

cv2.line(img, (100, 350), (400, 400), (0, 0, 255), 20, cv2.LINE_4)
cv2.line(img, (100, 400), (400, 450), (0, 0, 255), 20, cv2.LINE_8)
cv2.line(img, (100, 450), (400, 500), (0, 0, 255), 20, cv2.LINE_AA)
cv2.line(img, (0, 0), (500, 500), (0, 0, 255))

cv2.imshow('lines', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [83]:
def get_drawing_paper(H, W, mode='w', color=True):
    """ 빈 도화지 생성, 반환하는 함수 """
    # H : Height, W : Width
    if color:
        img = np.full((H, W, 3), 255 if mode=='w' else 0, dtype=np.uint8)
    else:
        img = np.full((H, W), 255, dtype=np.uint8)
    return img

In [145]:
def show_img_window(img, wait=0, title='default'):
    """ 지정한 시간(ms)만큼 보였다가 자동으로 꺼지는 창 생성하기 """
    cv2.imshow(title, img)
    print(cv2.getWindowImageRect(title))
    
    cv2.moveWindow(title, 100, 500)     # (제목, 가로, 세로)
    
    cv2.waitKey(wait)
    cv2.destroyAllWindows()

In [146]:
img = get_drawing_paper(700, 700, 'w')

In [147]:
show_img_window(img, 2000, 'art')

(999, 531, 700, 700)


얼굴인식

In [196]:
# 이미지 파일 및 정면얼굴 인식 모델 경로
frontalface_model = r'../data/haarcascades/haarcascade_frontalface_alt.xml'
img_file = r'../data/img/news_image.jpg'

In [197]:
# 정면얼굴 인식 모델 로딩
face_detector = cv2.CascadeClassifier(frontalface_model)

In [198]:
# 이미지 데이터 로딩
imgNP = cv2.imread(img_file)
imgNP.shape

# 이미지에서 정면 얼굴 인식 
face_detections = face_detector.detectMultiScale(imgNP)
print(f'** face_dections result\n{face_detections}')

** face_dections result
[[962 190 114 114]
 [212 175 132 132]]


In [199]:
# 인식된 정면 얼굴 ROI 표시
for (x, y, w, h) in face_detections:
    cv2.rectangle(imgNP, (x, y), (x + w, y + h), (0, 255, 0), 2)

# 화면 출력
cv2.imshow('[M]', imgNP)

# 키 입력 및 X버튼에 따른 창 닫기
if cv2.waitKey() or cv2.getWindowProperty('image', cv2.WND_PROP_VISIBLE) <1:
    cv2.destroyAllWindows()

동영상 프레임 읽기 : 책 25p 코드 참고