In [1]:
# 모듈 로딩
import numpy as np

In [4]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 => zeros()
np.zeros((2, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
# 1으로 채워진 ndarray 객체 생성 => ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2, 5), np.float16)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float16))

In [12]:
# 랜덤 데이터로 ndarray 객체 생성 => random
np.random.randint(1, 5, (3, 10))    # 이상, 미만, (shape)

array([[1, 3, 1, 1, 1, 1, 2, 1, 2, 3],
       [1, 3, 2, 2, 4, 3, 2, 4, 2, 1],
       [4, 4, 2, 2, 4, 3, 3, 3, 1, 4]])

In [13]:
# 0 <= 범위 < 1
np.random.rand(5, 2)    # shape (괄호없이)

array([[0.16412965, 0.87722002],
       [0.50330728, 0.63007966],
       [0.39355754, 0.53447107],
       [0.34548303, 0.67460682],
       [0.31539329, 0.21451359]])

In [14]:
# 표준정규분포
np.random.randn(5), np.random.randn(1, 2, 3)    # shape (괄호없이)

(array([0.13020815, 0.9818252 , 0.55125773, 1.60471954, 0.48016505]),
 array([[[ 0.15971274,  1.41983922, -0.67540378],
         [ 0.66749029,  0.03838515, -2.2140701 ]]]))

In [16]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [23]:
data = np.random.randn(10)
print(data)
np.random.shuffle(data)     # 랜덤하게 섞기 (파괴적)
print(data)

[ 0.80843557  0.03006708 -0.33617984  0.08126377 -0.24052418  2.03217933
  0.42584671 -1.68296489 -0.43388638 -1.41622753]
[-0.24052418  0.80843557  0.08126377  0.03006708 -0.33617984 -0.43388638
 -1.68296489  0.42584671  2.03217933 -1.41622753]


In [24]:
data.sum(), data.max(), data.min()

(-0.7319903512193269, 2.0321793255564504, -1.6829648888583426)

In [26]:
data.argmax(), data.argmin()

(8, 6)

In [29]:
data.flatten()  # 1차원으로 변경 (파괴적)

array([-0.24052418,  0.80843557,  0.08126377,  0.03006708, -0.33617984,
       -0.43388638, -1.68296489,  0.42584671,  2.03217933, -1.41622753])

In [30]:
data.ndim

1